### ISSUE TITLE
When I click on the "Tags" button, it doesn't show notes tags

### ISSUE THREAD

**Issue by classicrob** [raghuveerdotnet/simply-jekyll#11]
Hi! So, I recently tried adding tags to all of my pages (which are all within notes, no posts, I didn't care to differentiate between the two and didn't want to go through the date title naming convention) and nothing is showing up when I am on the tags page despite the fact that I have tags in the YAML front-matter for all of the pages that I want tags in. https://robhaisfield.com/tags/ Please advise! Here is my repo: https://github.com/classicrob/simply-jekyll

**Comment by raghuveerdotnet** [comment]
Hi Rob! 

It is probably because you changed the layout of the project. In the original theme, the tags are not counted for notes, only for posts. Anyway, I just took a look at your code, I think this should do it(specific to your usecase):

Add the following snippet  to the top of `content.html`. (If something like this already exists, replace that with the below snippet):
```liquid
<!-- Parse internal links, external links, transclusions etc and manipuate the content to reflect it accordingly -->
{%- if page.content-type == "notes" -%}
<ul class="tags">
    {%- if page.status != nil and page.status != empty -%}
    <li><a href="javascript:void(0)" class="tag"><b>Status:</b> <i>{{page.status | capitalize}}</i></a></li>
    {%- endif -%}
    <!-- Loop through page categories and print them in tags -->
    {%- if page.tags != empty and page.tags !=nil -%}
    {%- for tag in page.tags -%}
        <li><a href="/tags/#{{ tag }}" class="tag">{{ tag }}</a></li>
    {%- endfor -%}
    {%- endif -%}
</ul>
{%- endif -%}
```

Also replace the `<main>` portion inside `tags.md` with the below snippet (i.e. copy this with the similar snippet in your code):
```liquid
<main>
    {% assign tags =  site.notes | map: 'tags' | join: ' '  | split: ' ' | uniq %}
    {% for tag in tags %}
        <h3 id="{{ tag }}">{{ tag | captalize }}</h3>
        {%- for note in site.notes -%}
            {%- if note.tags contains tag -%}
                <li id="category-content" style="padding-bottom: 0.6em; list-style: none;"><a href="{{note.url}}">{{ note.title }}</a></li>
            {%- endif -%}
        {%- endfor -%}
    {%- endfor -%}
    <br/>
    <br/>
</main>
```
