### ISSUE TITLE
Great theme ! Here's some feedback.

### ISSUE THREAD

**Issue by Maxence-L** [raghuveerdotnet/simply-jekyll#13]
Dear Raghuveer,

I really like your theme, having looked for all of the alternatives digital garden platforms on the market. The tutorial on how to install it is one of the clearest I've read until now.

Having toyed a little bit with it, here is what I think could be improved :

- Notes .md files have tags, but there are not searchable by tags. Maybe the notes part could have a header including a 'tags' just as the home part ?

- It would make more sense to have all of the navigation links in one format than scattered in 3 formats (notes, header, '<- home') :
  - Instead of '<- Home' button inside articles, it would maybe be clearer to have a proper "Home" button in the header, next to "About".
  - Idem for notes, instead of a link, include it in the navigation header should make it easier for the reader to understand the hierarchy of the website. Besides, that leaves some room for a user-defined link, such as, for instance, a CV, a social media link, an alternative blog or a linked-in (or something else !).

I'm not really well-versed in html/CSS, but I may try to see i I can add a 'Home' button to the header.

General questions :

- You mention that it is not an infinite-scroll, but if the blog has 100+ articles, how do readers can attain the 100th post ? Do they have to search in the tags menu ?
- Is internal linking between posts and notes allowed ?
- Is there a way to remove the blog part to have only the notes part ? Some people may already have a blog and just need a platform to publish notes. 
(Edit: found later the [classicrob/simply-jekyll](https://github.com/classicrob/simply-jekyll) fork which does exactly this !)

Thanks for the good work !

**Comment by raghuveerdotnet** [comment]
Hello Maxence-L,

Thank you for your kind words. These are really good suggestions, some of what you've suggested can be incorporated into the theme, while the rest are design decisions that I took as I too am a beneficiary of this theme, so that might be difficult to change.

- **Tags in Notes:** You can already do that. If you mean a separate tab for tags in the notes section. That should be doable. (Please Clarify)
- **Navigation Hierarchy:** It used to be initially like that, but having 5 menu items(home, about, tags, notes, rss) makes the header feel too cluttered. This is what I meant by design decision. 
    - If you still want the five menu structure with **Home** and **Notes**, check out **https://intertexts.net** by Bopuc on twitter. They forked and modified **simply-jekyll**; and made it really good. I feel it caters to your taste, you might like that one more.
- There is no way to search chronologically other than just scroll all the way down to the 100th post, but you can always search for keywords in the search bar at the top.
- Yes, internal linking between posts and notes is allowed.
- Yes, Rob Haisfield did a pretty great job tweaking the theme. You can fork his copy and tinker with it. If you want something more, you can also look into Bopuc's version of simply-jekyll(mentioned above), he did a pretty great job too. 

Hope this answers your questions. Please do let me know if you still have any questions. 

Cheers! :)

**Comment by Maxence-L** [comment]
Great ! Thank you for your answer, I'm going to use Rob Haisfield's work as a starter. Bocup fork is quite neat too !
