### ISSUE TITLE
404 After Netlify Deploy

### ISSUE THREAD

**Issue by sansari** [raghuveerdotnet/simply-jekyll#2]
Hello,

I just so happened to have been helping a couple peers try to get their sites set up with these theme.

Upon deploying, they get a 404 as Netlify is not setting the deploy settings correctly. More here: https://twitter.com/daretorant/status/1275960558668279808?s=20

Would suggest adding to README or tutorial. Not sure if it’s something you can fix with the repo to have Netlify auto-set them.

**Comment by raghuveerdotnet** [comment]
Thanks for the heads up! This is happening because Netlify is setting up a web server and hosting the first HTML file it finds in the root directory as there is no specific directory that we specify for it to look into, but from what I understand Netlify should automatically detect from the project that it is a Jekyll project and apply those settings automatically. Not sure why that isn't happening. Anyway, I have changed the setup page with the manual change for the time being; will look into the auto-deployment option and ease up the process if possible. :)
